Makefile
srcs/Server.cpp

The push of the branch/issue 32 had an error that caused substr usage to throw an exception mid program and kill the server. That was corrected here

corrected exception after successful login

---

.gitignore
incl/Server.hpp
srcs/Server.cpp

When using C-c (SIGINT) or C-\ (SIGQUIT) the server will stop and close all connections and cleanup memory

31 implement sigint and sigquit detection in the server class

---

.github/workflows/build.yml

Github actions to verify if build is successful on each push and pull request to main

40 make GitHub actions to test a build on push and pull requests

---

Makefile
incl/Authenticator.hpp
incl/Server.hpp
srcs/Authenticator.cpp
srcs/Commands.cpp
srcs/Server.cpp

Here is the first version of the authenticator class. PLease review

Authenticator class

---

Makefile
incl/ACommand.hpp
incl/Authenticator.hpp
incl/CommandFactory.hpp
incl/Messenger.hpp
incl/NickCommand.hpp
incl/NoCommand.hpp
incl/PassCommand.hpp
incl/Server.hpp
incl/UserCommand.hpp
srcs/ACommand.cpp
srcs/Authenticator.cpp
srcs/CommandFactory.cpp
srcs/Messenger.cpp
srcs/NickCommand.cpp
srcs/NoCommand.cpp
srcs/PassCommand.cpp
srcs/Server.cpp
srcs/UserCommand.cpp

i think it should be working properly.

Replaced all instances where perror was called for throws

---

Makefile
incl/ACommand.hpp
incl/Authenticator.hpp
incl/CommandFactory.hpp
incl/Messenger.hpp
incl/NickCommand.hpp
incl/NoCommand.hpp
incl/PassCommand.hpp
incl/Server.hpp
incl/UserCommand.hpp
srcs/ACommand.cpp
srcs/Authenticator.cpp
srcs/CommandFactory.cpp
srcs/Messenger.cpp
srcs/NickCommand.cpp
srcs/NoCommand.cpp
srcs/PassCommand.cpp
srcs/Server.cpp
srcs/UserCommand.cpp
tests.sh

Creates 3 terminals, each with an authenticated user in nc, and kills them with Ctrl-C in the main terminal

Tests file

---

incl/Messenger.hpp
srcs/Messenger.cpp
srcs/Server.cpp

Deleted the corresponding function in Messenger and altered Server.cpp

no more large message constraints

---

Makefile
incl/ACommand.hpp
incl/CommandFactory.hpp
incl/Messenger.hpp
incl/Parser.hpp
incl/Server.hpp
incl/commands/JoinCommand.hpp
incl/commands/NickCommand.hpp
incl/commands/NoCommand.hpp
incl/commands/PassCommand.hpp
incl/commands/UserCommand.hpp
srcs/Authenticator.cpp
srcs/CommandFactory.cpp
srcs/Message.cpp
srcs/Messenger.cpp
srcs/Parser.cpp
srcs/Server.cpp
srcs/commands/JoinCommand.cpp
srcs/commands/NickCommand.cpp
srcs/commands/NoCommand.cpp
srcs/commands/PassCommand.cpp
srcs/commands/UserCommand.cpp

Separated Parser logic from Messenger class. 
With this separation, the Parser will return a ParsedMsg struct and Commands will return PreparedResponse.
Also, tried to simplify the listeningLoop flow in Server class.
Please check and advise :)

64 separate parser from messenger

---

incl/Channel.hpp
incl/ChannelManager.hpp
srcs/Channel.cpp
srcs/ChannelManager.cpp

With the integration with CommandFactory done, we can switch from saving nicks in the channel for having user's fds
Also, changed the functions Channel::isUser(int user), Channel::isOperator(int user) and Channel::setOperator(int user) to use the std::vector built-in methods.

Change to std::vector<int>

---

incl/ACommand.hpp
srcs/CommandFactory.cpp
srcs/commands/NamesCommand.cpp
srcs/commands/PassCommand.cpp
srcs/commands/UserCommand.cpp

NAMES command is preliminary since I can only test it properly when we have JOIN rocking

added PASS & USER already loggedin validation and NAMES command

---

bot/Makefile
bot/incl/ACommand.hpp
bot/incl/Chatbot.hpp
bot/srcs/Chatbot.cpp
bot/srcs/main.cpp
srcs/commands/NamesCommand.cpp

adapted names and moved bot's main function to classes

89 adapt names command to deal with operators too

---

incl/Message.hpp
srcs/Message.cpp
srcs/commands/InviteCommand.cpp
srcs/commands/JoinCommand.cpp
srcs/commands/KickCommand.cpp
srcs/commands/ModeCommand.cpp
srcs/commands/NamesCommand.cpp
srcs/commands/NickCommand.cpp
srcs/commands/PartCommand.cpp
srcs/commands/PassCommand.cpp
srcs/commands/PrivCommand.cpp
srcs/commands/UserCommand.cpp

Substituted all msgs in commands plus join,  invite and kick

54 substitute all  response attributions for calls to the functions of message

---

srcs/Server.cpp
srcs/commands/NickCommand.cpp
srcs/commands/UserCommand.cpp

Noticed meanwhile that users couldn't login via nc after the last couple of changes

corrected leaks and successful login not working

---

bot/srcs/Chatbot.cpp
bot/srcs/botcmds/NamesCommand.cpp
incl/Message.hpp
incl/UserManager.hpp
srcs/ACommand.cpp
srcs/Message.cpp
srcs/UserManager.cpp
srcs/commands/InviteCommand.cpp
srcs/commands/JoinCommand.cpp
srcs/commands/KickCommand.cpp
srcs/commands/ModeCommand.cpp
srcs/commands/NickCommand.cpp
srcs/commands/PassCommand.cpp
srcs/commands/PrivCommand.cpp
srcs/commands/UserCommand.cpp

adjusted some commands to work okay in hexchat

99 change bot invite from privmsg to normal invite command

---

incl/ACommand.hpp
incl/Channel.hpp
srcs/ACommand.cpp
srcs/Channel.cpp
srcs/Message.cpp
srcs/Messenger.cpp
srcs/commands/InviteCommand.cpp
srcs/commands/JoinCommand.cpp
srcs/commands/KickCommand.cpp
srcs/commands/ModeCommand.cpp
srcs/commands/NickCommand.cpp
srcs/commands/PartCommand.cpp
srcs/commands/PassCommand.cpp
srcs/commands/PrivCommand.cpp
srcs/commands/UserCommand.cpp

102 give command feedback to all involved channel users

---

incl/Channel.hpp
incl/ChannelManager.hpp
incl/Message.hpp
srcs/Channel.cpp
srcs/ChannelManager.cpp
srcs/Message.cpp
srcs/commands/ModeCommand.cpp

it will be fiiiiiiine.........

104 mode command should display all channel parameters

---

refs/tests.sh
srcs/Message.cpp
srcs/commands/NamesCommand.cpp
srcs/commands/PartCommand.cpp

Code adjustments

---

Makefile
incl/CommandFactory.hpp
incl/Message.hpp
incl/commands/TopicCommand.hpp
srcs/CommandFactory.cpp
srcs/Message.cpp
srcs/commands/KickCommand.cpp
srcs/commands/ModeCommand.cpp
srcs/commands/TopicCommand.cpp
srcs/commands/UserCommand.cpp

108 implement the topic command

---

incl/Message.hpp
srcs/Message.cpp
srcs/User.cpp
srcs/commands/InviteCommand.cpp
srcs/commands/JoinCommand.cpp
srcs/commands/KickCommand.cpp
srcs/commands/ModeCommand.cpp
srcs/commands/NamesCommand.cpp
srcs/commands/NickCommand.cpp
srcs/commands/PartCommand.cpp
srcs/commands/PrivCommand.cpp
srcs/commands/TopicCommand.cpp
srcs/commands/UserCommand.cpp

Mid testing

---

incl/Message.hpp
srcs/Message.cpp
srcs/commands/ModeCommand.cpp

refactored mode to accept one flag at the time

Simplified mode

---

Makefile
bot/Makefile
bot/incl/Chatbot.hpp
bot/srcs/Chatbot.cpp
bot/srcs/botcmds/NamesCommand.cpp
bot/srcs/main.cpp
srcs/Message.cpp
srcs/commands/KickCommand.cpp
srcs/commands/NamesCommand.cpp
srcs/commands/PrivCommand.cpp

Last corrections

---

Makefile
bot/Makefile
bot/incl/Chatbot.hpp
bot/srcs/Chatbot.cpp
bot/srcs/botcmds/NamesCommand.cpp
bot/srcs/main.cpp
srcs/Message.cpp
srcs/commands/KickCommand.cpp
srcs/commands/ModeCommand.cpp
srcs/commands/NamesCommand.cpp
srcs/commands/PrivCommand.cpp

Bot corrections

---

srcs/Message.cpp
srcs/commands/PrivCommand.cpp

corrected privmsg to be loggedin only

---

srcs/commands/NickCommand.cpp
srcs/commands/PassCommand.cpp
srcs/commands/UserCommand.cpp

corr msg order
